name = "duoreimi"

pages_build_output_dir = "."

[vars]
DASHSCOPE_API_KEY = "sk-ws-H.RELXYEY.Ad7O.MEUCIBy4na3T87NfUuSql9y80MoV8ErdhM8wISt2F59Mr6hiAiEA8c-hxdpYpxyOyFTbLVR89gkMMB5agyUHbnSGtp2MghY"
VOLC_API_KEY = "ark-6ffdce0b-648e-47b5-8682-7b7f18179522-5ba2a"